config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/about_us", to: 'pages#about_us'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :requests, only: [:new, :create]
  end
    delete "/cars/:id", to:"cars#destroy", as: :destroy_car

  resources :requests, except: [:new, :create, :index] do
    resources :reviews, only: [:new, :create, :index]
    member do
      post 'accept'
      post 'decline'
    end
  end
  delete "/requests/:id", to:"requests#destroy", as: :destroy_request
  resources :dashboards

  get "/dashboard/owner", to: "dashboards#owner"
  get "/dashboard/user", to: "dashboards#user"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :requests, dependent: :destroy
  has_many :reviews, through: :requests
  has_one_attached :photo

  validates :photo, presence: true
  validates :brand, presence: true
  validates :number_of_seats, presence: true
  validates :registration_number, presence: true, uniqueness: true
  validates :transmission, presence: true
  validates :price, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :location, presence: true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :car
  belongs_to :user
  belongs_to :review, optional: true

  validates :status, presence: true, inclusion: { in: ["pending", "accepted", "declined"] }

end

app/models/review.rb
class Review < ApplicationRecord
has_one :request
validates :rating, presence: true
validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cars
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @locations = Car.all.pluck(:location).uniq
    @cars = Car.all
    @cars = @cars.where(location: params[:location]) if params[:location].present?
    @cars = @cars.where("start_date <= ?", params[:start_date]) if params[:start_date].present?
    @cars = @cars.where("end_date >= ?", params[:end_date]) if params[:end_date].present?
    # @cars = @cars.where("location = ? AND start_date > ?", params[:location], params[:start_date]) if(params[:location].present? && params[:start_date].present?)
    # @cars = @cars.where("location = ? AND end_date < ?", params[:location], params[:end_date] ) if (params[:location].present? && params[:end_date].present?)
    # @cars = @cars.where("location = ? AND start_date > ? AND end_date < ?", params[:location], params[:start_date], params[:end_date]) if (params[:location].present? && params[:start_date].present? && params[:end_date].present?)
  end


    def show
      @car = Car.find(params[:id])
      @reviews = @car.reviews
    end

    def new
      @car = Car.new
    end

    def create
      @car = Car.new(car_params)
      @car.user = current_user
      if @car.save
        redirect_to dashboard_owner_path(@car.user)
      else
        render :new
      end
    end

    def edit
      @car = Car.find(params[:id])
      authorize_owner!(@car)
    end

    def update
      @car = Car.find(params[:id])
      authorize_owner!(@car)

      @car.update(car_params)
      @car.save
      redirect_to car_path(@car)
    end

    def destroy
      @car = Car.find(params[:id])
      authorize_owner!(@car)
      @car.destroy
      redirect_to dashboard_owner_path
    end

    private

    def car_params
      params.require(:car).permit(:brand, :price, :model, :number_of_seats, :registration_number, :transmission, :airconditioning, :year, :photo, :start_date, :end_date, :location)
    end

    def authorize_owner!(car)
      if current_user != car.user
        flash[:notice] = "Bad user."
        redirect_to cars_path
      end
    end
  end

# No user_id in the params YET !!
# No AVAILABILITY for Cars in the params YET !!

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    before_action :authenticate_user!

def owner
  # binding.pry
  @user = current_user
  @cars = Car.where(user_id: @user.id)
  @my_cars_requests = Request.where(car_id: @cars)
  # @reviews = @user.request.review

end

def user
  @user = current_user
  @requests = Request.where(user_id: @user.id)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about_us]

  def home
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_car, only: [:create, :new]

  def accept
    @request = Request.find(params[:id])
    @request.status = "accepted"
    @request.save
    redirect_to dashboard_owner_path
  end

  def decline
    @request = Request.find(params[:id])
    @request.status = "declined"
    @request.save
    redirect_to dashboard_owner_path
  end

  def index
  @requests = Request.all
  end

  def show
    @request = Request.find(params[:id])
    @car = @request.car
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    @request.car = @car
    @request.user = current_user
    if @request.save
      redirect_to dashboard_user_path
    else
      render :new
    end
  end

  # def edit
  #   @request = Request.find(params[:id])
  # end

  # def update
  #   @request = Request.find(params[:id])
  #   @request.update(request_params)
  #   @request.save
  #   redirect_to request_path(@request)
  # end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_back(fallback_location: root_path)
  end

  private

   def set_car
    @car = Car.find(params[:car_id])
  end

  def request_params
    params.require(:request).permit(:drop_off_date, :pick_up_date)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @request = Request.find(params[:request_id])
    @review = Review.new()
  end

  def create
    @request = Request.find(params[:request_id])
    @car = @request.car
    @review = Review.new(review_params)
    @review.request = @request
    if @review.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  private
  def review_params
    params.require(:review).permit(:rating, :text, :request_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_form.html.erb
<%= simple_form_for(@car) do |f| %>
          <div class="form-group">
          <%= f.input :brand %>
          <%= f.input :model %>
          <%= f.input :year, input_html: { min: '0' } %>
          <%= f.input :price, input_html: { min: '0' } %>
          <%= f.input :number_of_seats, collection: 1..8 %>
          <%= f.input :registration_number %>
          <%= f.input :start_date %>
          <%= f.input :end_date %>
          <%= f.input :location %>
          <%= f.input :transmission, collection: ['Automatic', 'Manual'] %>
          <%= f.input :airconditioning %>
          <%= f.input :photo, as: :file %>
<!--           f.input :photo, as: :file -->
<!--           f.input :availability -->
          <%= f.button :submit, "List Your Car", {class: "btn btn-primary"} %>
          </div>
        <% end %>

app/views/cars/delete.html.erb
<h1>Cars#delete</h1>
<p>Find me in app/views/cars/delete.html.erb</p>

app/views/cars/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <h1>Update your car details</h1>
        <%= render 'form'%>
        <%= link_to "Back",  cars_path, {class: "btn btn-primary"} %>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 offset-3">
      <h1>Add your own car</h1>
        <%= render 'form'%>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container mt-5">
  <div class="grid">
  <!--   <div class="box box0">
      <h1>Details of your car</h1>
    </div> -->
    <div class="box box1">
      <p><%= @car.brand %> <%=@car.model%> (<%=@car.year%>)</p>
      <% 5.times do %>
      <i class="fa fa-star"></i>
      <% end %>
      <p>€<%= @car.price %></p>
      <div class="icon_show d-flex mt-3">
        <%= image_tag "calendar.png"%>
        <div class="ml-3">
          <h6> <strong>From:</strong> <%= @car.start_date %></h6>
          <h6> <strong>To:</strong> <%= @car.end_date %></h6>
        </div>
      </div>
      <div class="nested mt-3">
        <div>
          <p class="car_components">AC</p>
          <% if @car.airconditioning == true %>
          <span>Yes</span>
          <% else %>
          <span>No</span>
          <% end %>
        </div>
        <div>
          <p class="car_components">Seats</p>
          <h6><%= @car.number_of_seats %></h6>
        </div>
        <div>
          <p class="car_components">Transmission</p>
          <h6><%= @car.transmission.capitalize %></h6>
        </div>
      </div>
      <img src="" alt="">
      <img src="" alt="">
    </div>

    <div class="show_car_img box box2">
     <div class="card-picture">
      <%= cl_image_tag @car.photo.attached? ? @car.photo.key : "injcuuecln8fvf2vo2zg", width: 500, height: 350, crop: :fill, :cloud_name => "dir0nw4ok"%>
       <i class="map-pin-logo fas fa-map-marker-alt"></i> <p class="car-location"> <%= @car.location %></p>
     </div>
    </div>

    <div class="btn-box1">
      <% if current_user == @car.user %>
      <%= link_to "Update",  edit_car_path, {class: "btn btn-primary"} %>
      <%= link_to "Delete", car_path(@car), class: "btn btn-primary", method: :delete, data: { confirm: "Are you sure?"} %>
      <%= link_to "Back",  cars_path, {class: "btn btn-primary"} %>
      <% else %>
      <%= link_to "Back",  cars_path, {class: "btn btn-outline-warning text-dark"} %>
      <%= link_to "Request Now",  new_car_request_path(@car), {class: "btn btn-success request-btn"} %>
      <% end %>
    </div>

    <div class="box3">
      <h2>
        <%= pluralize @car.reviews.size, "review" %>
      </h2>
      <div class="cards_review">
        <%  if @car.reviews.blank? %>
          Be the first to leave a review for <%= @car.brand %> <%=@car.model %> !!
          <% else %>
        <% @reviews.each do |review| %>
        <div class="card-review">
          <% counter = 0 %>
          <% 5.times do %>
          <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
          <% counter += 1 %>
          <% end %>
          <% end %>
        <h6><%= review.text %></h6>
        </div>
       <% end %>
      </div>
    </div>
  </div>

app/views/dashboards/owner.html.erb
<div class="container">
  <div class="row">
    <div class="d-flex profile-container justify-content-center">
      <!-- user profile harcoded for now -->
      <div class="profile-card">
        <div>
          <h3>Personal Info</h3>
          <p><%= @user.first_name.capitalize %> <%=@user.last_name.capitalize %></p>
          <img class="avatar-large" alt="avatar" src="https://images.unsplash.com/photo-1565464027194-7957a2295fb7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=80" />
        </div>
        <div class="profile-content">
          <p>"I travel for business a couple times a month, and I appreciate the possibility to park my car at the airport hussle-free while making some money when I am away."</p>
          <p>Home Location: Amsterdam</p>
          <p>Review Score: 4.8</p>
        </div>
      </div>
      <!-- manage cars container, add or remove, update cars, cars cards -->
      <div class="container manage-cars justify-content-center align-items-center">
       <div class="d-flex justify-content-end">
        <%= link_to "Rent a car", dashboard_user_path(@user), class: "btn btn-primary" %>
      </div>
      <% if @cars.count < 2 %>
      <h2>Manage your car</h2>
      <% else %>
      <h2>Manage your cars</h2>
      <% end %>
      <div class="index-car-card-grid ">
        <% @cars.each do |car| %>
        <div class="index-car-card-owner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path car.photo.attached? ? car.photo.key : "injcuuecln8fvf2vo2zg", width: 100, height: 100, crop: :fill, :cloud_name => "dir0nw4ok"%>');">
          <p><%= link_to "#{car.brand}", car_path(car.id) %></p>
          <%= link_to car_path(car), class: 'car-delete', method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="fas fa-trash-alt"></i>
          <% end %>
        </div>
        <% end %>
      </div>
      <% if @cars.empty? %>
      <%= link_to "List your car", new_car_path(request), class: "btn btn-primary", id: "upload_car" %>
      <% else %>
      <%= link_to "Add another car", new_car_path(request), class: "btn btn-primary", id: "upload_car" %>
      <% end %>
    </div>
  </div>
</div>
</div>
<div class="container">
  <div class="">
    <div class="d-flex requests-container justify-content-center">
      <div>
        <% if @my_cars_requests.blank? %>
        <%= " " %>
        <% else %>
        <% if @my_cars_requests.count < 2 %>
        <h2 class="text-center mb-4">Rent Request</h2>
        <% else %>
        <h2 class="text-center mb-4">Rent Requests</h2>
        <% end %>
         <% end %>
        <% @my_cars_requests.each do |request|%>
          <div class="request-cards ">
            <div class="request-card d-flex">
              <%= cl_image_tag request.car.photo.attached? ? request.car.photo.key : "injcuuecln8fvf2vo2zg", width: 500, height: 350, crop: :fill, :cloud_name => "dir0nw4ok"%>
            <div class="request-card-info">
              <h4>Car: <%=request.car.brand %></h4>
              <p>Status: <%= request.status %></p>
              <p>Pickup date: <%= request.pick_up_date%></p>
              <p>Return date: <%= request.drop_off_date%></p>
            </div>
            <% if  request.status == "pending"%>
              <button type="button" class="btn btn-primary accept-btn" data-toggle="modal" data-target="#accept-<%=request.id%>">
                Accept
              </button>
              <button type="button" class="btn btn-primary decline-btn" data-toggle="modal" data-target="#decline-<%=request.id%>">
                Decline
              </button>
            <% end %>


            <!-- Modal -->
            <div class="modal fade" id="accept-<%=request.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Accept Request</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Are you sure??
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    <%= link_to "Accept", accept_request_path(request), method: :post, class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="decline-<%=request.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Decline Request</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Are you sure??
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    <%= link_to "Decline", decline_request_path(request), method: :post, class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- end of my requests cards, including modals -->
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/dashboards/user.html.erb
<div class="container">
  <div class="row">
    <div class="d-flex profile-container justify-content-center">
      <!-- user profile harcoded for now -->
      <div class="manage-cars ">
        <div class="d-flex justify-content-between">
          <%= link_to "List your own car", dashboard_owner_path(@user), class: "btn btn-primary" %>
          <%= link_to "Rent a car", cars_path(request), class: "btn btn-primary" %>
        </div>
        <h3>Your Rent Requests</h3>
        <% @requests.each do |request|%>
        <div class="card-product">
          <%= cl_image_tag request.car.photo.attached? ? request.car.photo.key : "injcuuecln8fvf2vo2zg", width: 500, height: 350, crop: :fill, :cloud_name => "dir0nw4ok"%>
          <div class="card-product-infos">
            <h4>Car: <%= request.car.brand %></h4>
            <p>Pickup date: <%= request.pick_up_date %></p>
            <p>Return date: <%= request.drop_off_date %></p>
            <p>Status: <%= request.status %></p>
            <%= link_to "Cancel request", destroy_request_path(request), method: :delete, class: "delete-btn btn btn-primary btn-sm" %>
          </div>
        </div>
        <% end %>
      </div>
      <div class="profile-card">
        <div>
          <h3>Personal Info</h3>
          <p><%= @user.first_name.capitalize %> <%=@user.last_name.capitalize %></p>
          <img class="avatar-large" alt="avatar" src="https://images.unsplash.com/photo-1565464027194-7957a2295fb7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=80" />
        </div>
        <div class="profile-content">
          <p>"I travel for business a couple times a month, and I appreciate the possibility to park my car at the airport hussle-free while making some money when I am away."</p>
          <p>Home Location: Amsterdam</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="">

    <div class="">
      <% if @requests.blank? %>
      <% " " %>
      <% else %>
      <% if @requests.count < 2%>
      <h4 class="text-center mb-4">Previous booking</h4>
      <% else %>
      <h4 class="text-center mb-4">Previous bookings</h4>
      <% end %>
      <% end %>
      <div class="request-cards">

      <% @requests.where("status = ? AND drop_off_date < ?", "accepted", Date.today ).each do |request|%>
      <div class="request-card d-flex ">
        <%= cl_image_tag request.car.photo.attached? ? request.car.photo.key : "injcuuecln8fvf2vo2zg", width: 500, height: 350, :cloud_name => "dir0nw4ok"%>
        <div class="request-card-info ">
          <h2>Car: <%= request.car.brand %></h2>
          <p>Pickup date: <%= request.pick_up_date %></p>
          <p>Return date: <%= request.drop_off_date %></p>
        </div>
          <div>
          <%= link_to "review", new_request_review_path(request),  class: "review-btn btn btn-primary btn-sm" %>
        </div>
      </div>
      <% end %>
      </div>
    </div>
  </div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://www.bestholidaytips.co.uk/wp-content/uploads/2018/07/hiring-a-car-on-holiday.jpg);">
  <div class="container">
    <h1>  <strong>VAYCAR</strong>!</h1>
    <p>The easy way to rent or park your car at the airport.</p>
  </div>
</div>

<div class="cards d-flex justify-content-center">
  <div class="card text-center" style="width: 24rem;">
    <img class="card-img-top" src="https://www.directverzekerd.nl/wp-content/uploads/2016/10/car-key-in-hand.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">List your car here!</h5>
      <p class="card-text">You want to <strong>earn money</strong> while on <strong>holiday</strong>.</p>
      <%= link_to "Add your car",  new_car_path, {class: "card_action btn btn-primary"} %>
    </div>
  </div>

  <div class="card text-center" style="width: 24rem;">
    <img class="card-img-top" src="https://www.creterentcar.com/wp-content/uploads/2016/10/021-rent-a-car-in-crete-car-rental-crete-rent-a-car-crete-crete-car-rental-crete-car-hire-crete-autorental-crete-rent-986x500.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Find your car!</h5>
      <p class="card-text">You want to rent a car at <strong>the airport</strong>.</p>
      <%= link_to "Search a car",  cars_path, {class: "card_action btn btn-primary"} %>
    </div>
  </div>
</div>

<div class="reviews-container">
<h3 id="reviews-header">Customer Reviews</h3>
<div class="reviews-home d-flex justify-content-center">

  <div class="review-card">
    <div class="review-header">
      <h4>Great Idea</h4>
      <img class="avatar review-avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/cveneziani" />
    </div>
    <div class="review-content">
      <p class="review-text">Easy to use so much quicker than using the car hire centre at the airport. Very reasonably priced and both staff members i dealt with were very friendly and upbeat, nice to be welcomed by a smiling face. Will use again.</p>
      <span class="star-rating"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></span>
      <p class="review-author">Caroline Baird</p>
      <p class="review-place">Amsterdam, NL</p>
    </div>
  </div>

  <div class="review-card">
    <div class="review-header">
      <h4>Impressive</h4>
      <img class="avatar review-avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />
    </div>
    <div class="review-content">
      <p class="review-text">Very impressed! We left our car with Vaycar when on a 2 week holiday and were very pleased with the service, and we made some profit. Will definitely be doing this again!</p>
      <span class="star-rating"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></span>
      <p class="review-author">Bryan Smith</p>
      <p class="review-place">Miami, FL, USA</p>
    </div>
  </div>

  <div class="review-card">
    <div class="review-header">
      <h4>Amazing!</h4>
      <img class="avatar review-avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/krokrob" />
    </div>
    <div class="review-content">
      <p class="review-text">Service was excellent! Staff are friendly and engaged. Appreciated being contacted directly by an actual person whom I can reply to by phone or text if I need help.</p>
      <span class="star-rating"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></span>
      <p class="review-author">Ray Foster</p>
      <p class="review-place">Brisbane, AUS</p>
    </div>
  </div>

  <div class="review-card">
    <div class="review-header">
      <h4>Yay VayCar!</h4>
      <img class="avatar review-avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/sarahlafer" />
    </div>
    <div class="review-content">
      <p class="review-text">Quick, easy and comfortably my most pleasurable experience hiring a car. Paula at Gatwick airport was very friendly and professional. The next time I am at Gatwick and hiring a car there is only one place I will be thinking of.</p>
      <span class="star-rating"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></span>
      <p class="review-author">Maria Thompson</p>
      <p class="review-place">London, UK</p>
    </div>
  </div>
</div>
</div>

app/views/requests/index.html.erb
<h1>all the requests</h1>
<% @requests.each do |request| %>

<p><%=request.car.brand%></p>
<p><%=  request.drop_off_date%></p>
<p><%=  request.pick_up_date%></p>


<% end %>

<%= link_to "request", new_request_path(:car_id), class: "btn btn-primary btn-lg" %>
<%= link_to "back to cars", cars_path, class: "btn btn-primary btn-lg" %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@request, @review] do |f| %>
<div class="form-group">
  <%= f.input :rating, collection: 1..5 %>
  <%= f.input :text %>
  <%= f.button :submit, {class: "btn btn-primary"}%>
</div>
<% end %>

app/views/reviews/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <h1>Reviews</h1>
      <% @reviews.each do |review| %>
        <p>Rating: <%= review.rating %></p>
        <p>Review: <%= review.text %></p>
      <% end %>
      <%= link_to "Add review",  new_request_review_path, {class: "btn btn-primary"} %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
 <div class="container">
  <div class="row">
    <div class="col-6 offset-3">
            <h1>Your review</h1>
              <p>Rating: <%= @review.rating %></p>
              <p>Review: <%= @review.text %></p>
              <%= link_to "All reviews",  reviews_path, {class: "btn btn-primary"} %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path  do %>
    <%= image_tag "VAYCAR.png"%>
    <% end %>
    <%= link_to "Park and Rent my Car", new_car_path , class: "toplinks nav-link" %>
    <%= link_to "Rent a Car", cars_path, class: "toplinks nav-link" %>
    <%= link_to "Our Guarantee", "#", class: "toplinks nav-link" %>
    <%= link_to "About Us", about_us_path, class: "toplinks nav-link" %>
    <%= link_to "Help & Support", "#", class: "toplinks nav-link" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://images.unsplash.com/photo-1565464027194-7957a2295fb7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.cars.any? %>
            <%= link_to "Dashboard", dashboard_owner_path, class: "dropdown-item" %>
            <% else %>
            <%= link_to "Dashboard", dashboard_user_path, class: "dropdown-item" %>
            <%end  %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-primary text-white" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>